
new_objects_mpcat40_mapping = {'AlarmClockVintage': 'objects', 'BathSheetBlue': 'objects', 'BathTowelPink': 'objects', 'CDrack': 'shelving',
                               'CatObject': 'objects', 'CrackersBox': 'objects', 'CubeBox': 'objects', 'CutleryBlockSet': 'objects',
                               'DishTowel': 'objects', 'DogBowlBlue': 'objects', 'DogFoobler': 'objects', 'Elephant': 'objects', 'EyeCream': 'objects',
                               'FabricBasket': 'objects', 'FabricCube': 'objects', 'Fedora': 'objects', 'FileSorterPink': 'objects', 'GardenSwing': 'objects',
                               'GigabyteBox': 'objects', 'KidsPack': 'objects', 'KitchenTowel': 'objects', 'Notebook': 'objects',
                               'PepsiBox': 'objects', 'PitcherWhite': 'objects', 'PlantContainerQuadra': 'objects', 'PlantContainerUrn': 'objects',
                               'PlantPot': 'plant', 'PorcelainRamekin': 'objects', 'PowerPressureCooker': 'objects', 'ReversibleBookend': 'objects',
                               'RollLearnTurtle': 'objects', 'RoundPlanterRed': 'objects', 'Sandwich': 'objects', 'StackRings': 'objects', 'SteelMilkFrother': 'objects',
                               'StorageBinBlack': 'objects', 'TeaSet': 'objects', 'TeapotWhite': 'objects', 'TucanFrame': 'picture', 'TwistedPuzzle': 'objects',
                               'UpFlippinDog': 'objects', 'VeniceFrame': 'picture', 'VitaminCEster': 'objects', 'aquarium': 'objects', 'armchair2': 'chair',
                               'armchair3': 'chair', 'baguettePain': 'objects', 'banana': 'objects', 'bdOuverte': 'objects', 'blackTupelo': 'objects',
                               'blocks': 'objects', 'bookcase': 'shelving', 'bouilloire': 'objects', 'bucket': 'objects', 'cardboard-box': 'objects',
                               'chair_office': 'chair', 'chaiseOrange': 'chair', 'cheezit': 'objects', 'chefcan': 'objects', 'clothes-basket': 'furniture',
                               'comoCiliegio': 'cabinet', 'couchPoofyPillows': 'sofa', 'couchTable': 'table', 'credenza': 'cabinet', 'cup': 'objects',
                               'cup2': 'objects', 'desserte': 'shelving', 'fanPalm': 'objects', 'flowers': 'plant', 'frame3VerticalSummerPhotos': 'picture',
                               'frame3VerticalTowerPhotos': 'picture', 'frame_horizontal': 'picture', 'frame_square': 'picture', 'gardenUmbrella': 'furniture',
                               'hallTable': 'table', 'japanese_style_screen': 'furniture', 'lamp2': 'lighting', 'largeclamp': 'objects', 'leather_sofa': 'sofa',
                               'letters': 'objects', 'livres': 'objects', 'modern_armchair': 'chair', 'officeChair': 'chair', 'percolateur': 'objects',
                               'pizza': 'objects', 'plancheADecouper': 'objects', 'potplant2': 'plant', 'rocking_chair': 'chair', 'roundTable2': 'table', 'rug': 'objects',
                               'rug2': 'objects', 'secheCheveux': 'objects', 'shelves_storage_wood': 'furniture', 'singleChair': 'chair', 'small_bookshelves': 'shelving',
                               'smiley': 'objects', 'sneakers': 'objects', 'sofa4': 'sofa', 'sofa_white_beige': 'sofa', 'stair_ladder_loft': 'stairs', 'stairs_spiral': 'stairs',
                               'table': 'table', 'table_granmother_marble': 'table', 'throwPillow': 'cushion', 'toast': 'objects',
                               'toothpaste_brush': 'objects', 'wheelie_bin': 'objects', 'wine_bottle': 'objects'}

object_loc = {
    'mug': ['table', 'cabinet', 'furniture', 'sink', 'toilet'],
    'bottle': ['table', 'cabinet', 'furniture', 'sink'],
    'pot': ['floor'],
    'bowl': ['table', 'cabinet', 'furniture', 'sink'],
    'chair': ['floor'],
    'table': ['floor'],
    'clock': ['table', 'furniture', 'cabinet'],
    'bag': ['table', 'cabinet', 'furniture', 'chair', 'sofa', 'bed', 'counter', 'seating'],
    'sofa': ['floor'],
    'laptop': ['table', 'cabinet', 'bed'],
    'bed': ['floor'],
    'microwave': ['table', 'bed', 'furniture'],
    'cabinet': ['floor'],
    'bookshelf': ['floor'],
    'stove': ['floor', 'table', 'furniture'],
    'printer': ['floor', 'table'],
    'pillow': ['sofa', 'bed', 'table'],
    'etc': ['sofa', 'bed', 'table', 'counter', 'seating', 'furniture', 'cabinet', 'chest_of_drawers', 'sink', 'appliances', 'chair', 'stool'],
}